apiVersion: platform.infraforge.io/v1
kind: ApplicationClaim
metadata:
  name: gitops-managed-app
  namespace: default
spec:
  namespace: gitops-apps
  environment: production
  owner:
    team: DevOps Team
    email: devops@example.com
  # ArgoCD ile yönetilecek uygulamalar
  gitops:
    enabled: true
    argocd:
      namespace: argocd
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      repositories:
        - url: https://github.com/your-org/app-configs
          path: environments/production
          targetRevision: main
  # Direkt deployment'lar
  applications:
    - name: frontend
      version: v2.0.0
      replicas: 3
      repository: github.com/your-org/frontend
      gitops:
        enabled: true  # Bu app ArgoCD tarafından yönetilecek
        path: k8s/overlays/production
    - name: backend
      version: v1.5.0
      replicas: 5
      repository: github.com/your-org/backend
      gitops:
        enabled: false  # Bu app direkt deploy edilecek
  components:
    - type: postgresql
      name: main-db
      version: "14"
    - type: redis
      name: cache
      version: "7.0"