apiVersion: platform.infraforge.io/v1
kind: OperatorCatalog
metadata:
  name: cloudnativepg
  displayName: CloudNativePG Operator
  description: Kubernetes operator for PostgreSQL with high availability and backup
  category: operator
  icon: https://cloudnative-pg.io/images/hero-operator.svg
  documentation: https://cloudnative-pg.io/documentation/

spec:
  # Operator installation details
  installation:
    method: helm
    repository: https://cloudnative-pg.github.io/charts
    chart: cloudnative-pg
    version: "0.20.0"
    namespace: cnpg-system  # Operator namespace
    createNamespace: true

  # Operator capabilities
  capabilities:
    - name: cluster-management
      description: Manage PostgreSQL clusters
    - name: automated-failover
      description: Automatic failover and self-healing
    - name: backup-recovery
      description: Backup to S3/Azure/GCS and point-in-time recovery
    - name: connection-pooling
      description: PgBouncer integration for connection pooling
    - name: monitoring
      description: Prometheus metrics and Grafana dashboards

  # Custom Resource Definitions managed by this operator
  crds:
    - name: Cluster
      group: postgresql.cnpg.io
      version: v1
      description: PostgreSQL cluster definition
    - name: Backup
      group: postgresql.cnpg.io
      version: v1
      description: On-demand backup
    - name: ScheduledBackup
      group: postgresql.cnpg.io
      version: v1
      description: Scheduled backup configuration
    - name: Pooler
      group: postgresql.cnpg.io
      version: v1
      description: PgBouncer pooler configuration

  # Resource requirements for operator itself
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  # Monitoring
  monitoring:
    enabled: true
    serviceMonitor: true
