apiVersion: v1
kind: Secret
metadata:
  name: gitea-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: http://gitea-http.gitea.svc.cluster.local:3000/infraforge/voltran.git
  username: gitea_admin
  password: gitea_admin