# Development Profile Overrides for Percona MongoDB
# These values override or extend the base template

# Minimal setup for development
replsets:
  - name: rs0
    size: 1
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi

# No backup in dev
backup:
  enabled: false

# No monitoring in dev
pmm:
  enabled: false

# No TLS in dev
tls:
  mode: disabled

# Simple connection settings
configuration:
  net:
    maxIncomingConnections: 1000
  operationProfiling:
    mode: off
  storage:
    wiredTiger:
      engineConfig:
        cacheSizeGB: 0.5