# Production Profile Overrides for Percona MongoDB
# Full-featured enterprise setup

replsets:
  - name: rs0
    size: 5
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      minAvailable: 3
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: "2"
        memory: 4Gi
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: fast-ssd
        resources:
          requests:
            storage: 200Gi
    # Non-voting members for read scaling
    nonvoting:
      enabled: true
      size: 2
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi

# Sharding enabled
sharding:
  enabled: true
  configsvrReplSet:
    size: 3
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  mongos:
    size: 3
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi

# Advanced backup with PITR
backup:
  enabled: true
  pitr:
    enabled: true
    oplogSpanMin: 60
    compressionType: zstd
    compressionLevel: 6
  storages:
    minio-primary:
      type: s3
      s3:
        bucket: mongodb-backups-prod
        endpointUrl: http://infraforge-minio.infraforge-storage:9000
        serverSideEncryption:
          sseAlgorithm: AES256
    nfs-secondary:
      type: filesystem
      filesystem:
        persistentVolumeClaim:
          storageClassName: nfs-backup
          resources:
            requests:
              storage: 500Gi
  tasks:
    - name: incremental-30min
      enabled: true
      schedule: "*/30 * * * *"
      keep: 48
      storageName: minio-primary
      type: incremental
      compressionType: zstd
      compressionLevel: 6
    - name: daily-full
      enabled: true
      schedule: "0 2 * * *"
      keep: 7
      storageName: minio-primary
      type: full
      compressionType: zstd
      compressionLevel: 9
    - name: weekly-nfs
      enabled: true
      schedule: "0 3 * * 0"
      keep: 8
      storageName: nfs-secondary
      type: full
      compressionType: zstd
      compressionLevel: 9
    - name: monthly-archive
      enabled: true
      schedule: "0 4 1 * *"
      keep: 12
      storageName: minio-primary
      type: full
      compressionType: zstd
      compressionLevel: 9

# Advanced monitoring
pmm:
  enabled: true
  serverHost: pmm-server.infraforge-monitoring
  resources:
    limits:
      cpu: 600m
      memory: 600Mi
    requests:
      cpu: 300m
      memory: 300Mi
  args:
    - "--disable-tablestats-limit=2000"
    - "--disable-queryexamples=false"
    - "--query-source=profiler"
    - "--max-slowlog-size=1073741824"

# Required TLS
tls:
  mode: requireTLS
  certValidityDuration: 8760h
  issuerConf:
    name: mongodb-ca-issuer
    kind: Issuer
    group: cert-manager.io

# Production configuration
configuration:
  net:
    maxIncomingConnections: 65536
    compression:
      compressors: snappy,zstd,zlib
  operationProfiling:
    mode: slowOp
    slowOpThresholdMs: 50
  storage:
    directoryPerDB: true
    wiredTiger:
      engineConfig:
        cacheSizeGB: 4
        journalCompressor: zstd
        directoryForIndexes: true
      collectionConfig:
        blockCompressor: zstd
  replication:
    oplogSizeMB: 10240
  security:
    enableEncryption: true
    redactClientLogData: true
  setParameter:
    ttlMonitorSleepSecs: 60
    wiredTigerConcurrentReadTransactions: 128
    wiredTigerConcurrentWriteTransactions: 128
    transactionLifetimeLimitSeconds: 300