{{- if .Values.backup.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.clusterName }}-scheduled-backup
  namespace: {{ .Values.namespace }}
  labels:
    app: postgresql-backup
    tenant: {{ .Values.tenant }}
    environment: {{ .Values.environment }}
    managed-by: infraforge
spec:
  # Schedule in cron format
  schedule: {{ .Values.backup.schedule | quote }}

  # Backup owner reference
  backupOwnerReference: self

  # Target cluster
  cluster:
    name: {{ .Values.clusterName }}

  # Immediate backup on schedule creation
  immediate: true

  # Suspend backups if needed (for maintenance)
  suspend: false
{{- end }}
