apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: infraforge-platform
  description: InfraForge Cloud Platform System
  tags:
    - platform
    - kubernetes
    - aws
  links:
    - url: https://argocd.infraforge.io
      title: ArgoCD Dashboard
      icon: dashboard
    - url: https://grafana.infraforge.io
      title: Grafana Monitoring
      icon: dashboard
    - url: https://github.com/NimbusProTch/PaaS-Platform
      title: GitHub Repository
      icon: github
spec:
  owner: platform-team
  domain: cloud-platform

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: kratix-control-plane
  description: Kratix Platform Orchestrator
  annotations:
    backstage.io/kubernetes-id: kratix-control-plane
    backstage.io/kubernetes-namespace: kratix-platform-system
    argocd/app-name: kratix-control-plane
  tags:
    - kratix
    - platform
    - control-plane
  links:
    - url: https://kratix.io
      title: Kratix Documentation
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: infraforge-platform
  dependsOn:
    - resource:kubernetes-cluster
    - component:argocd-gitops

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: argocd-gitops
  description: GitOps Controller
  annotations:
    backstage.io/kubernetes-id: argocd
    backstage.io/kubernetes-namespace: infraforge-argocd
  tags:
    - gitops
    - argocd
    - cd
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: infraforge-platform
  providesApis:
    - argocd-api
  dependsOn:
    - resource:kubernetes-cluster