injector:
  enabled: false
  replicas: 1
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m

server:
  ha:
    enabled: false
    replicas: 1
    raft:
      enabled: false
  
  standalone:
    enabled: true
  
  dataStorage:
    size: 1Gi
  
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m
  
  ingress:
    enabled: true