apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: microservice-template
  title: Microservice Template
  description: Create a new microservice with all platform integrations
  tags:
    - recommended
    - microservice
    - golang
    - nodejs
    - python
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Service Information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name for the service
          pattern: '^[a-z0-9-]+$'
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: What does this service do?
        owner:
          title: Owner
          type: string
          description: Owner team
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group

    - title: Technology Stack
      required:
        - language
        - framework
      properties:
        language:
          title: Programming Language
          type: string
          description: Choose the programming language
          enum:
            - golang
            - nodejs
            - python
            - java
          enumNames:
            - 'Go'
            - 'Node.js'
            - 'Python'
            - 'Java'
        framework:
          title: Framework
          type: string
          description: Choose the framework
          enum:
            - gin
            - fiber
            - express
            - fastapi
            - flask
            - springboot
          enumNames:
            - 'Gin (Go)'
            - 'Fiber (Go)'
            - 'Express (Node.js)'
            - 'FastAPI (Python)'
            - 'Flask (Python)'
            - 'Spring Boot (Java)'

    - title: Infrastructure Requirements
      properties:
        database:
          title: Database
          type: object
          properties:
            enabled:
              title: Enable Database
              type: boolean
              default: false
            type:
              title: Database Type
              type: string
              enum:
                - postgresql
                - mysql
                - mongodb
                - redis
            size:
              title: Storage Size
              type: string
              default: '10Gi'
              enum:
                - '10Gi'
                - '20Gi'
                - '50Gi'
                - '100Gi'
        cache:
          title: Caching
          type: object
          properties:
            enabled:
              title: Enable Cache
              type: boolean
              default: false
            type:
              title: Cache Type
              type: string
              default: redis
              enum:
                - redis
                - memcached
        messaging:
          title: Messaging
          type: object
          properties:
            enabled:
              title: Enable Messaging
              type: boolean
              default: false
            type:
              title: Messaging Type
              type: string
              enum:
                - rabbitmq
                - kafka
                - nats
        storage:
          title: Object Storage
          type: object
          properties:
            enabled:
              title: Enable Object Storage
              type: boolean
              default: false
            size:
              title: Storage Size
              type: string
              default: '10Gi'

    - title: Deployment Configuration
      properties:
        environments:
          title: Environments
          type: array
          description: Select deployment environments
          items:
            type: string
            enum:
              - development
              - staging
              - production
          default:
            - development
        resources:
          title: Resource Limits
          type: object
          properties:
            cpu:
              title: CPU Limit
              type: string
              default: '500m'
              enum:
                - '250m'
                - '500m'
                - '1000m'
                - '2000m'
            memory:
              title: Memory Limit
              type: string
              default: '512Mi'
              enum:
                - '256Mi'
                - '512Mi'
                - '1Gi'
                - '2Gi'
        replicas:
          title: Initial Replicas
          type: integer
          default: 2
          minimum: 1
          maximum: 10
        autoscaling:
          title: Enable Autoscaling
          type: boolean
          default: true

    - title: Observability
      properties:
        monitoring:
          title: Monitoring
          type: object
          properties:
            enabled:
              title: Enable Monitoring
              type: boolean
              default: true
            customDashboard:
              title: Create Custom Dashboard
              type: boolean
              default: true
        tracing:
          title: Distributed Tracing
          type: object
          properties:
            enabled:
              title: Enable Tracing
              type: boolean
              default: true
        logging:
          title: Logging Level
          type: string
          default: 'info'
          enum:
            - debug
            - info
            - warn
            - error

    - title: Repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.com

  steps:
    # Fetch base template
    - id: fetch
      name: Fetch Base Template
      action: fetch:template
      input:
        url: ./skeleton/${{ parameters.language }}
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          language: ${{ parameters.language }}
          framework: ${{ parameters.framework }}

    # Generate Kubernetes manifests
    - id: generate-k8s
      name: Generate Kubernetes Manifests
      action: fetch:template
      input:
        url: ./k8s-templates
        targetPath: ./k8s
        values:
          name: ${{ parameters.name }}
          environments: ${{ parameters.environments }}
          resources: ${{ parameters.resources }}
          replicas: ${{ parameters.replicas }}
          autoscaling: ${{ parameters.autoscaling }}

    # Generate CI/CD pipelines
    - id: generate-ci
      name: Generate CI/CD Pipeline
      action: fetch:template
      input:
        url: ./ci-templates/${{ parameters.language }}
        targetPath: ./.github/workflows
        values:
          name: ${{ parameters.name }}
          language: ${{ parameters.language }}
          framework: ${{ parameters.framework }}

    # Create Kratix promise for infrastructure
    - id: create-promise
      name: Create Infrastructure Promise
      action: kratix:promise:create
      input:
        name: ${{ parameters.name }}
        tenant: ${{ parameters.owner }}
        database: ${{ parameters.database }}
        cache: ${{ parameters.cache }}
        messaging: ${{ parameters.messaging }}
        storage: ${{ parameters.storage }}

    # Register in catalog
    - id: register
      name: Register in Software Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

    # Create monitoring dashboards
    - id: create-dashboards
      name: Create Monitoring Dashboards
      if: ${{ parameters.monitoring.customDashboard }}
      action: grafana:dashboard:create
      input:
        name: ${{ parameters.name }}-dashboard
        service: ${{ parameters.name }}
        metrics:
          - request_rate
          - error_rate
          - latency_p99
          - cpu_usage
          - memory_usage

    # Publish to GitHub
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        gitCommitMessage: 'Initial commit for ${{ parameters.name }}'
        gitAuthorName: 'Backstage'
        gitAuthorEmail: 'backstage@infraforge.io'
        topics:
          - microservice
          - ${{ parameters.language }}
          - ${{ parameters.framework }}

    # Create ArgoCD application
    - id: create-argocd-app
      name: Create ArgoCD Application
      action: argocd:create:application
      input:
        name: ${{ parameters.name }}
        repoUrl: ${{ steps['publish'].output.remoteUrl }}
        path: k8s/overlays/development
        project: ${{ parameters.owner }}

  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}
      - title: View in ArgoCD
        icon: dashboard
        url: https://argocd.infraforge.io/applications/${{ parameters.name }}
      - title: View Monitoring Dashboard
        icon: dashboard
        url: https://grafana.infraforge.io/d/${{ parameters.name }}
      - title: View Logs
        icon: analytics
        url: https://grafana.infraforge.io/explore?left=%7B%22queries%22:%5B%7B%22expr%22:%22%7Bapp%3D%5C%22${{ parameters.name }}%5C%22%7D%22%7D%5D%7D