apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: default
type: Opaque
data:
  username: Z2Fza2luaW1idXNwcm8=  # gaskinimbuspro
  password: Z2hwX3Q0YzNGamRaUzRmeE9jZm5JZ1dMM25HSG0xa0wycjBieFFmeg==  # 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
---
apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: kratix-platform-system
type: Opaque
data:
  username: Z2Fza2luaW1idXNwcm8=  # gaskinimbuspro
  password: Z2hwX3Q0YzNGamRaUzRmeE9jZm5JZ1dMM25HSG0xa0wycjBieFFmeg==  # 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