apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: default
type: Opaque
data:
  username: aW5mcmFmb3JnZQ==  # infraforge
  password: Z2hwX3F4aEdnWW5adlBpM2czRVVHNGR3VVJYZ2hVd2FjZzNGSEFhQw==  # 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
---
apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: kratix-platform-system
type: Opaque
data:
  username: aW5mcmFmb3JnZQ==  # infraforge
  password: Z2hwX3F4aEdnWW5adlBpM2czRVVHNGR3VVJYZ2hVd2FjZzNGSEFhQw==  # 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