apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: default
type: Opaque
data:
  username: Z2Fza2luaW1idXNwcm8=  # gaskinimbuspro
  password: Z2hwX3ZVUEdRYmxvZUxzYU5wbmhjQ3I2S091VkdPSlBWbzQzT2t0Sg==  # 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
---
apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: kratix-platform-system
type: Opaque
data:
  username: Z2Fza2luaW1idXNwcm8=  # gaskinimbuspro
  password: Z2hwX3ZVUEdRYmxvZUxzYU5wbmhjQ3I2S091VkdPSlBWbzQzT2t0Sg==  # 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