apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: default
type: Opaque
data:
  username: Z2Fza2luMQ==  # gaskin1
  password: Z2hwX1BMSkdWWWV3SmR1VjlRalQ3bXRlNWd6NlFvdDVSQzNMemsyTQ==  # token
---
apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
  namespace: kratix-platform-system
type: Opaque
data:
  username: Z2Fza2luMQ==  # gaskin1
  password: Z2hwX1BMSkdWWWV3SmR1VjlRalQ3bXRlNWd6NlFvdDVSQzNMemsyTQ==  # token