# InfraForge Platform Promise
# Self-service platform for deploying databases and middleware
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: infraforge
  namespace: kratix-platform-system
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: infraforges.platform.infraforge.io
    spec:
      group: platform.infraforge.io
      scope: Namespaced
      names:
        plural: infraforges
        singular: infraforge
        kind: InfraForge
        shortNames:
        - if
        - infra
      versions:
      - name: v1
        served: true
        storage: true
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                required:
                - tenant
                - environment
                properties:
                  tenant:
                    type: string
                    description: Team or department name (e.g., finance, marketing)
                    pattern: '^[a-z][a-z0-9-]*$'
                  environment:
                    type: string
                    description: Target environment
                    enum:
                    - dev
                    - test
                    - uat
                    - prod
                  business:
                    type: array
                    description: Business applications
                    items:
                      type: object
                      required:
                      - name
                      - enabled
                      properties:
                        name:
                          type: string
                          description: Application name
                          enum:
                          - backoffice
                          - frontend
                          - nginx
                          - webapp
                        enabled:
                          type: boolean
                          description: Enable/disable this application
                        profile:
                          type: string
                          description: Deployment profile
                          enum:
                          - dev
                          - standard
                          - production
                          default: dev
                  platform:
                    type: array
                    description: Platform services
                    items:
                      type: object
                      required:
                      - name
                      - enabled
                      properties:
                        name:
                          type: string
                          description: Platform service name
                          enum:
                          - vault
                          - istio
                          - keycloak
                          - grafana
                        enabled:
                          type: boolean
                          description: Enable/disable this service
                        profile:
                          type: string
                          description: Deployment profile
                          enum:
                          - dev
                          - standard
                          - production
                          default: dev
                  operators:
                    type: array
                    description: Database operators
                    items:
                      type: object
                      required:
                      - name
                      - enabled
                      properties:
                        name:
                          type: string
                          description: Operator name
                          enum:
                          - postgresql
                          - mongodb
                          - redis
                          - kafka
                          - rabbitmq
                        enabled:
                          type: boolean
                          description: Enable/disable this operator
                        profile:
                          type: string
                          description: Deployment profile (nonprod or prod)
                          enum:
                          - nonprod
                          - prod
                          default: nonprod
        additionalPrinterColumns:
        - name: Tenant
          type: string
          jsonPath: .spec.tenant
        - name: Environment
          type: string
          jsonPath: .spec.environment
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
  destinationSelectors:
  - matchLabels:
      infraforge.io/platform: "true"
  workflows:
    promise:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: promise-configure
        spec:
          containers:
          - name: promise-configure
            image: busybox:1.36
            command: ["/bin/sh", "-c", "echo 'InfraForge Promise configured'"]
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: resource-configure
        spec:
          containers:
          - name: infraforge-generator
            image: infraforge-generator:latest
            imagePullPolicy: Never
            command: ["/app/generator"]
            env:
            - name: ENABLE_GIT_SYNC
              value: "true"
            - name: KRATIX_WORKFLOW_TYPE
              value: "resource"
            - name: GIT_REPO_URL
              value: "https://github.com/NimbusProTch/PaaS-Platform.git"
            - name: GIT_BRANCH
              value: "main"