# Additional RBAC for Kratix to manage InfraForge resources
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kratix-infraforge-manager
rules:
- apiGroups:
  - platform.infraforge.io
  resources:
  - infraforges
  - infraforges/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kratix-infraforge-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kratix-infraforge-manager
subjects:
- kind: ServiceAccount
  name: kratix-platform-controller-manager
  namespace: kratix-platform-system