apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: infraforge-platform
  namespace: kratix-platform-system
spec:
  api:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: infraforges.platform.infraforge.io
    spec:
      group: platform.infraforge.io
      versions:
      - name: v1
        served: true
        storage: true
        schema:
          openAPIV3Schema:
            type: object
            properties:
              spec:
                type: object
                properties:
                  tenant:
                    type: string
                    description: Tenant identifier
                  environment:
                    type: string
                    enum: ["dev", "staging", "prod"]
                    description: Target environment
                  region:
                    type: string
                    default: "eu-west-1"
                    description: AWS Region for deployment

                  # Database Configuration
                  database:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: false
                      type:
                        type: string
                        enum: ["postgresql", "mysql", "mongodb"]
                        default: "postgresql"
                      version:
                        type: string
                        default: "16.1"
                      replicas:
                        type: integer
                        minimum: 1
                        maximum: 5
                        default: 1
                      storage:
                        type: string
                        pattern: '^[0-9]+Gi$'
                        default: "10Gi"
                      backup:
                        type: object
                        properties:
                          enabled:
                            type: boolean
                            default: false
                          schedule:
                            type: string
                            default: "0 2 * * *"
                          retention:
                            type: string
                            default: "7d"
                      highAvailability:
                        type: boolean
                        default: false
                      resources:
                        type: object
                        properties:
                          requests:
                            type: object
                            properties:
                              cpu:
                                type: string
                                default: "500m"
                              memory:
                                type: string
                                default: "1Gi"
                          limits:
                            type: object
                            properties:
                              cpu:
                                type: string
                                default: "2000m"
                              memory:
                                type: string
                                default: "4Gi"

                  # Cache Configuration
                  cache:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: false
                      type:
                        type: string
                        enum: ["redis", "memcached"]
                        default: "redis"
                      replicas:
                        type: integer
                        default: 1
                      persistence:
                        type: boolean
                        default: false
                      resources:
                        type: object
                        properties:
                          requests:
                            type: object
                            properties:
                              cpu:
                                type: string
                                default: "100m"
                              memory:
                                type: string
                                default: "256Mi"

                  # Message Queue Configuration
                  messaging:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: false
                      type:
                        type: string
                        enum: ["rabbitmq", "kafka", "sqs"]
                        default: "rabbitmq"
                      replicas:
                        type: integer
                        default: 1
                      highAvailability:
                        type: boolean
                        default: false
                      resources:
                        type: object
                        properties:
                          requests:
                            type: object
                            properties:
                              cpu:
                                type: string
                                default: "500m"
                              memory:
                                type: string
                                default: "1Gi"

                  # Object Storage Configuration
                  objectStorage:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: false
                      type:
                        type: string
                        enum: ["minio", "s3"]
                        default: "minio"
                      replicas:
                        type: integer
                        default: 1
                      storage:
                        type: string
                        default: "20Gi"
                      buckets:
                        type: array
                        items:
                          type: string
                      resources:
                        type: object
                        properties:
                          requests:
                            type: object
                            properties:
                              cpu:
                                type: string
                                default: "500m"
                              memory:
                                type: string
                                default: "1Gi"

                  # Secrets Management
                  secretsManagement:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: false
                      type:
                        type: string
                        enum: ["vault", "aws-secrets-manager", "sealed-secrets"]
                        default: "vault"
                      autoUnseal:
                        type: boolean
                        default: false

                  # Monitoring and Observability
                  observability:
                    type: object
                    properties:
                      metrics:
                        type: boolean
                        default: true
                      logs:
                        type: boolean
                        default: true
                      traces:
                        type: boolean
                        default: false

                  # Networking
                  networking:
                    type: object
                    properties:
                      ingress:
                        type: object
                        properties:
                          enabled:
                            type: boolean
                            default: false
                          className:
                            type: string
                            default: "nginx"
                          tls:
                            type: boolean
                            default: false
                          domain:
                            type: string
                      serviceMesh:
                        type: object
                        properties:
                          enabled:
                            type: boolean
                            default: false
                          type:
                            type: string
                            enum: ["istio", "linkerd"]
                            default: "istio"

                  # Auto-scaling
                  autoscaling:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: false
                      minReplicas:
                        type: integer
                        default: 1
                      maxReplicas:
                        type: integer
                        default: 10
                      targetCPU:
                        type: integer
                        default: 80

                required:
                - tenant
                - environment
      scope: Namespaced
      names:
        plural: infraforges
        singular: infraforge
        kind: InfraForge
        shortNames:
        - if

  workflows:
    resource:
      configure:
      - apiVersion: platform.kratix.io/v1alpha1
        kind: Pipeline
        metadata:
          name: resource-configure
        spec:
          containers:
          - name: generate-manifests
            image: ghcr.io/nimbusprotech/infraforge-generator:latest
            command:
            - /bin/sh
            - -c
            - |
              # This is where the go-platform-generator runs
              # It reads the InfraForge CR and generates all necessary manifests
              /app/generator --input /kratix/input --output /kratix/output
            env:
            - name: GIT_REPO_URL
              value: "https://github.com/NimbusProTch/PaaS-Platform.git"
            - name: GIT_BRANCH
              value: "feature/production-ready-platform"

  destinations:
  - apiVersion: platform.kratix.io/v1alpha1
    kind: BucketStateStore
    metadata:
      name: platform-manifests
    spec:
      bucketName: infraforge-platform-manifests
      endpoint: https://s3.eu-west-1.amazonaws.com