apiVersion: platform.infraforge.io/v1
kind: ApplicationClaim
metadata:
  name: ecommerce-apps
  namespace: default
spec:
  environment: dev
  clusterType: nonprod
  giteaURL: http://gitea-http.gitea.svc.cluster.local:3000
  organization: infraforge

  owner:
    team: platform-team
    email: platform@infraforge.io
    slack: "#platform-dev"

  applications:
    - name: product-service
      enabled: true
      chart:
        name: microservice
        version: "1.0.0"
      image:
        repository: ghcr.io/nimbusprotch/product-service
        tag: "latest"
      serviceName: product-service
      version: v1.0.0
      replicas: 1

      ports:
        - name: http
          port: 8080
          protocol: TCP

      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"

      env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "8080"

    - name: user-service
      enabled: true
      chart:
        name: microservice
        version: "1.0.0"
      image:
        repository: ghcr.io/nimbusprotch/user-service
        tag: "latest"
      serviceName: user-service
      version: v1.0.0
      replicas: 1

      ports:
        - name: http
          port: 8081
          protocol: TCP

      resources:
        requests:
          cpu: "50m"
          memory: "64Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"

      env:
        - name: ENVIRONMENT
          value: "development"
        - name: PORT
          value: "8081"