apiVersion: platform.infraforge.io/v1
kind: ApplicationClaim
metadata:
  name: ecommerce-apps
  namespace: default
  labels:
    environment: dev
    team: platform-team
    project: ecommerce
    type: applications
spec:
  environment: dev
  clusterType: nonprod

  # GitOps configuration
  giteaURL: http://gitea-http.gitea.svc.cluster.local:3000
  organization: infraforge

  owner:
    team: platform-team
    email: platform@infraforge.io
    slack: "#platform-dev"

  # E-commerce Microservices
  applications:
    # Product Service (Node.js)
    - name: product-service
      chart:
        name: microservice
        version: "1.0.0"
      image:
        repository: ghcr.io/nimbusprotch/product-service
        tag: v1.0.0
      serviceName: product-service
      version: v1.0.0
      replicas: 2

      ports:
        - name: http
          port: 8080
          protocol: TCP
        - name: metrics
          port: 9090
          protocol: TCP

      healthCheck:
        path: /health
        port: 8080
        initialDelaySeconds: 40
        periodSeconds: 10

      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"

      env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "8080"
        - name: DATABASE_URL
          value: "postgresql://product_user:product_pass@product-db:5432/product_db"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: AMQP_URL
          value: "amqp://guest:guest@rabbitmq:5672"
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"

    # User Service (Go)
    - name: user-service
      chart:
        name: microservice
        version: "1.0.0"
      image:
        repository: ghcr.io/nimbusprotch/user-service
        tag: v1.0.0
      serviceName: user-service
      version: v1.0.0
      replicas: 2

      ports:
        - name: http
          port: 8081
          protocol: TCP

      healthCheck:
        path: /health
        port: 8081
        initialDelaySeconds: 40
        periodSeconds: 10

      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "400m"
          memory: "512Mi"

      env:
        - name: ENVIRONMENT
          value: "development"
        - name: PORT
          value: "8081"
        - name: DB_HOST
          value: "user-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "user_service"
        - name: DB_PASSWORD
          value: "user_pass"
        - name: DB_NAME
          value: "user_db"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: AMQP_URL
          value: "amqp://guest:guest@rabbitmq:5672/"

    # Order Service (Go)
    - name: order-service
      chart:
        name: microservice
        version: "1.0.0"
      image:
        repository: ghcr.io/nimbusprotch/order-service
        tag: v1.0.0
      serviceName: order-service
      version: v1.0.0
      replicas: 2

      ports:
        - name: http
          port: 8082
          protocol: TCP

      healthCheck:
        path: /health
        port: 8082
        initialDelaySeconds: 40
        periodSeconds: 10

      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "400m"
          memory: "512Mi"

      env:
        - name: ENVIRONMENT
          value: "development"
        - name: PORT
          value: "8082"
        - name: DB_HOST
          value: "order-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "order_user"
        - name: DB_PASSWORD
          value: "order_pass"
        - name: DB_NAME
          value: "order_db"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: AMQP_URL
          value: "amqp://guest:guest@rabbitmq:5672/"

    # Payment Service (Node.js)
    - name: payment-service
      chart:
        name: microservice
        version: "1.0.0"
      image:
        repository: ghcr.io/nimbusprotch/payment-service
        tag: v1.0.0
      serviceName: payment-service
      version: v1.0.0
      replicas: 2

      ports:
        - name: http
          port: 8083
          protocol: TCP
        - name: metrics
          port: 9090
          protocol: TCP

      healthCheck:
        path: /health
        port: 8083
        initialDelaySeconds: 40
        periodSeconds: 10

      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"

      env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "8083"
        - name: DATABASE_URL
          value: "postgresql://payment_user:payment_pass@payment-db:5432/payment_db"
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: AMQP_URL
          value: "amqp://guest:guest@rabbitmq:5672"
        - name: STRIPE_SECRET_KEY
          value: "sk_test_dummy"

    # Notification Service (Go)
    - name: notification-service
      chart:
        name: microservice
        version: "1.0.0"
      image:
        repository: ghcr.io/nimbusprotch/notification-service
        tag: v1.0.0
      serviceName: notification-service
      version: v1.0.0
      replicas: 1

      ports:
        - name: http
          port: 8084
          protocol: TCP

      healthCheck:
        path: /health
        port: 8084
        initialDelaySeconds: 40
        periodSeconds: 10

      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"

      env:
        - name: ENVIRONMENT
          value: "development"
        - name: PORT
          value: "8084"
        - name: DB_HOST
          value: "notification-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "notification_user"
        - name: DB_PASSWORD
          value: "notification_pass"
        - name: DB_NAME
          value: "notification_db"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: AMQP_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        - name: SMTP_HOST
          value: "smtp.gmail.com"
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_FROM
          value: "noreply@infraforge.io"
