apiVersion: platform.infraforge.io/v1
kind: ApplicationClaim
metadata:
  name: ecommerce-platform
  namespace: default
  labels:
    environment: dev
    team: platform-team
spec:
  environment: dev

  owner:
    team: platform-team
    email: platform@infraforge.io
    slack: "#platform-dev"

  applications:
    - name: ecommerce-api
      serviceName: ecommerce-platform
      version: v1.0.0
      replicas: 2

      ports:
        - name: http
          port: 8080
          protocol: TCP

      healthCheck:
        path: /health
        port: 8080
        initialDelaySeconds: 30
        periodSeconds: 10

      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"

      env:
        - name: LOG_LEVEL
          value: "debug"
        - name: ENVIRONMENT
          value: "development"
        - name: PORT
          value: "8080"

  components:
    - type: postgresql
      name: main-db
      version: "15"
      storage: 10Gi
      replicas: 1
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "1000m"
          memory: "2Gi"
