apiVersion: platform.infraforge.io/v1
kind: PlatformApplicationClaim
metadata:
  name: ecommerce-infrastructure
  namespace: default
  labels:
    environment: dev
    team: platform-team
    project: ecommerce
    type: infrastructure
spec:
  environment: dev
  clusterType: nonprod

  owner:
    team: platform-team
    email: platform@infraforge.io
    slack: "#platform-dev"

  # Infrastructure Components - Shared platform services
  services:
    # PostgreSQL Databases (one per microservice)
    - type: postgresql
      name: product-db
      version: "15"
      size: medium
      chart:
        name: postgresql
        version: "1.0.0"
      values:
        persistence:
          size: 20Gi
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"

    - type: postgresql
      name: user-db
      version: "15"
      size: small
      chart:
        name: postgresql
        version: "1.0.0"
      values:
        persistence:
          size: 10Gi
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

    - type: postgresql
      name: order-db
      version: "15"
      size: medium
      chart:
        name: postgresql
        version: "1.0.0"
      values:
        persistence:
          size: 20Gi
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1000m"
            memory: "2Gi"

    - type: postgresql
      name: payment-db
      version: "15"
      size: small
      chart:
        name: postgresql
        version: "1.0.0"
      values:
        persistence:
          size: 10Gi
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

    - type: postgresql
      name: notification-db
      version: "15"
      size: small
      chart:
        name: postgresql
        version: "1.0.0"
      values:
        persistence:
          size: 5Gi
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

    # Shared Services
    - type: redis
      name: redis
      version: "7"
      size: small
      chart:
        name: redis
        version: "1.0.0"
      values:
        persistence:
          size: 5Gi
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"

    - type: rabbitmq
      name: rabbitmq
      version: "3.12"
      size: medium
      chart:
        name: rabbitmq
        version: "1.0.0"
      values:
        persistence:
          size: 10Gi
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"

    - type: elasticsearch
      name: elasticsearch
      version: "8.11"
      size: large
      chart:
        name: elasticsearch
        version: "1.0.0"
      values:
        persistence:
          size: 30Gi
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "1000m"
            memory: "4Gi"
