---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ui
  namespace: microservices
  labels:
    app: ecommerce-ui
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-ui
  template:
    metadata:
      labels:
        app: ecommerce-ui
        version: v1
    spec:
      containers:
      - name: ecommerce-ui
        image: localhost:5000/ecommerce-ui:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://api-gateway.microservices:8000"
        - name: NEXT_PUBLIC_USER_SERVICE_URL
          value: "http://user-service.microservices:8081"
        - name: NEXT_PUBLIC_PRODUCT_SERVICE_URL
          value: "http://product-service.microservices:8080"
        - name: NEXT_PUBLIC_ORDER_SERVICE_URL
          value: "http://order-service.microservices:8082"
        - name: NEXT_PUBLIC_PAYMENT_SERVICE_URL
          value: "http://payment-service.microservices:8083"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ui
  namespace: microservices
  labels:
    app: ecommerce-ui
spec:
  selector:
    app: ecommerce-ui
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: LoadBalancer