---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: microservices
  labels:
    app: notification-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8084"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: notification-service
        image: microservices-notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8084
          name: http
        env:
        - name: DB_HOST
          value: "postgresql.infrastructure"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_NAME
          value: "notifications"
        - name: RABBITMQ_URL
          value: "amqp://rabbitmq:rabbitmq@rabbitmq.infrastructure:5672/"
        - name: SMTP_HOST
          value: "smtp.gmail.com"
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-secret
              key: password
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: twilio-secret
              key: account-sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: twilio-secret
              key: auth-token
        - name: TWILIO_FROM
          valueFrom:
            secretKeyRef:
              name: twilio-secret
              key: from-number
        - name: JAEGER_ENDPOINT
          value: "http://jaeger-collector.infrastructure:14268/api/traces"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8084
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8084
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microservices
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
    name: http
  type: ClusterIP