---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: microservices
  labels:
    app: web-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
        version: v1
    spec:
      containers:
      - name: web-frontend
        image: localhost:5000/web-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://api-gateway.microservices:8000"
        - name: NEXT_PUBLIC_USER_SERVICE_URL
          value: "http://user-service.microservices:8081"
        - name: NEXT_PUBLIC_PRODUCT_SERVICE_URL
          value: "http://product-service.microservices:8080"
        - name: NEXT_PUBLIC_ORDER_SERVICE_URL
          value: "http://order-service.microservices:8082"
        - name: NEXT_PUBLIC_PAYMENT_SERVICE_URL
          value: "http://payment-service.microservices:8083"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: microservices
  labels:
    app: web-frontend
spec:
  selector:
    app: web-frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  type: LoadBalancer