apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
    tenant: {{ .Values.tenant }}
    environment: {{ .Values.environment }}
    profile: prod
    managed-by: infraforge
spec:
  clusterSize: {{ .Values.replicas }}
  kubernetesConfig:
    image: redis:{{ .Values.redisVersion }}
    imagePullPolicy: IfNotPresent
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storage.storageClass }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
  redisExporter:
    enabled: {{ .Values.monitoring.enabled }}
    image: quay.io/opstree/redis-exporter:latest
  resources: {{- toYaml .Values.resources | nindent 4 }}
