apiVersion: v1
kind: Secret
metadata:
  name: ghcr-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: nimbusprotch-oci
  enableOCI: "true"
  url: ghcr.io/nimbusprotch
  username: nimbusprotch
  password: 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