apiVersion: v1
kind: Secret
metadata:
  name: github-repo
  namespace: infraforge-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  type: Z2l0  # git
  url: aHR0cHM6Ly9naXRodWIuY29tL2dhc2tpbjEvUGFhUy1QbGF0Zm9ybS5naXQ=  # https://github.com/gaskin1/PaaS-Platform.git
  username: Z2Fza2luMQ==  # gaskin1
  password: Z2hwX1BMSkdWWWV3SmR1VjlRalQ3bXRlNWd6NlFvdDVSQzNMemsyTQ==  # token