apiVersion: v1
kind: Secret
metadata:
  name: github-repo
  namespace: infraforge-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  type: Z2l0  # base64 of "git"
  url: aHR0cHM6Ly9naXRodWIuY29tL05pbWJ1c1Byb1RjaC9QYWFTLVBsYXRmb3Jt  # https://github.com/NimbusProTch/PaaS-Platform
  password: Z2hwX3F4aEdnWW5adlBpM2czRVVHNGR3VVJYZ2hVd2FjZzNGSEFhQw==  # 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
  username: aW5mcmFmb3JnZQ==  # infraforge