apiVersion: platform.infraforge.io/v1
kind: ServiceCatalog
metadata:
  name: postgresql
  displayName: PostgreSQL Database
  description: CloudNativePG-managed PostgreSQL with high availability
spec:
  type: database
  category: database

  dependencies:
    - name: cloudnativepg
      type: operator
      version: ">=1.22.0"

  profiles:
    - name: nonprod
      description: Single instance PostgreSQL for development
      default: true
      features:
        - Single instance
        - Basic monitoring
        - No backup

    - name: prod
      description: HA PostgreSQL cluster with backup
      features:
        - 3-instance HA cluster
        - Automated backup
        - Connection pooling
        - Advanced monitoring
