apiVersion: platform.infraforge.io/v1
kind: ServiceCatalog
metadata:
  name: postgresql
  displayName: PostgreSQL Database
  description: CloudNativePG-managed PostgreSQL with high availability, automated backup, and monitoring
  category: database
  icon: https://www.postgresql.org/media/img/about/press/elephant.png
  documentation: https://cloudnative-pg.io/
  tags:
    - database
    - sql
    - postgres
    - relational

spec:
  # Azure equivalent mapping
  azureEquivalent:
    service: "Azure Database for PostgreSQL"
    description: "On-premise alternative to Azure PostgreSQL with same enterprise features"

  # Requires CloudNativePG operator
  dependencies:
    - name: cloudnativepg
      type: operator
      version: ">=1.22.0"
      required: true

  # Available profiles
  profiles:
    - name: nonprod
      displayName: Non-Production
      description: Single instance PostgreSQL for development and testing
      useCase: Development, testing, and staging environments
      features:
        - Single instance (no HA)
        - Basic monitoring
        - No automated backup
        - Standard storage
      cost: Low

    - name: prod
      displayName: Production
      description: High-availability PostgreSQL cluster with backup and connection pooling
      useCase: Production workloads requiring HA, backup, and performance
      features:
        - 3-instance HA cluster
        - Automated failover
        - S3/MinIO backup with point-in-time recovery
        - PgBouncer connection pooling
        - Advanced monitoring and alerting
        - Pod anti-affinity for resilience
      cost: Medium-High

  # Parameters that can be customized per deployment
  parameters:
    # PostgreSQL version
    - name: postgresVersion
      displayName: PostgreSQL Version
      type: string
      default: "16.1"
      allowed: ["15.5", "16.1"]
      description: PostgreSQL major version

    # Storage configuration
    - name: storageSize
      displayName: Storage Size
      type: string
      default: "10Gi"
      profiles: [nonprod]
      description: Persistent storage size for nonprod
      pattern: "^[0-9]+Gi$"

    - name: storageSize
      displayName: Storage Size
      type: string
      default: "100Gi"
      profiles: [prod]
      description: Persistent storage size for production
      pattern: "^[0-9]+Gi$"

    - name: storageClass
      displayName: Storage Class
      type: string
      default: "standard"
      profiles: [nonprod]
      description: Kubernetes storage class

    - name: storageClass
      displayName: Storage Class
      type: string
      default: "fast-ssd"
      profiles: [prod]
      description: Fast SSD storage class for production

    # Replica configuration
    - name: replicas
      displayName: Number of Instances
      type: integer
      default: 1
      profiles: [nonprod]
      minimum: 1
      maximum: 1
      description: Single instance for nonprod

    - name: replicas
      displayName: Number of Instances
      type: integer
      default: 3
      profiles: [prod]
      minimum: 3
      maximum: 5
      description: Number of PostgreSQL instances in HA cluster

    # Database configuration
    - name: maxConnections
      displayName: Max Connections
      type: integer
      default: 100
      profiles: [nonprod]
      description: Maximum number of concurrent connections

    - name: maxConnections
      displayName: Max Connections
      type: integer
      default: 500
      profiles: [prod]
      description: Maximum number of concurrent connections

    # Backup configuration (prod only)
    - name: backupEnabled
      displayName: Enable Automated Backup
      type: boolean
      default: false
      profiles: [nonprod]
      description: Backup disabled for nonprod

    - name: backupEnabled
      displayName: Enable Automated Backup
      type: boolean
      default: true
      profiles: [prod]
      description: Enable automated backup to S3/MinIO

    - name: backupSchedule
      displayName: Backup Schedule
      type: string
      default: "0 2 * * *"
      profiles: [prod]
      description: Cron schedule for automated backups (default: 2 AM daily)

    - name: backupRetention
      displayName: Backup Retention
      type: string
      default: "30d"
      profiles: [prod]
      description: Backup retention period

    # Connection pooler (prod only)
    - name: poolerEnabled
      displayName: Enable Connection Pooler
      type: boolean
      default: false
      profiles: [nonprod]
      description: PgBouncer pooler disabled for nonprod

    - name: poolerEnabled
      displayName: Enable Connection Pooler
      type: boolean
      default: true
      profiles: [prod]
      description: Enable PgBouncer connection pooler

    - name: poolerReplicas
      displayName: Pooler Replicas
      type: integer
      default: 3
      profiles: [prod]
      description: Number of PgBouncer replicas

  # Resource requirements per profile
  resources:
    nonprod:
      postgresql:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 2000m
          memory: 4Gi

    prod:
      postgresql:
        requests:
          cpu: 2000m
          memory: 4Gi
        limits:
          cpu: 4000m
          memory: 8Gi
      pooler:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 256Mi

  # Monitoring & Observability
  monitoring:
    enabled: true
    exporter: postgres_exporter
    metrics:
      - pg_stat_activity
      - pg_stat_database
      - pg_stat_replication
      - pg_locks
    dashboards:
      - name: cloudnativepg-cluster
        description: CloudNativePG cluster overview
      - name: cloudnativepg-database
        description: Database-level metrics
    alerts:
      - name: PostgreSQLDown
        severity: critical
        description: PostgreSQL instance is down
      - name: PostgreSQLHighConnections
        severity: warning
        description: Connection count approaching limit
      - name: PostgreSQLReplicationLag
        severity: warning
        description: Replication lag is high
        profiles: [prod]
      - name: PostgreSQLBackupFailed
        severity: critical
        description: Backup job failed
        profiles: [prod]

  # Secrets and outputs
  outputs:
    - name: app-secret
      description: Application connection credentials
      type: secret
      keys:
        - name: host
          description: PostgreSQL service hostname
        - name: port
          description: PostgreSQL service port
          default: "5432"
        - name: dbname
          description: Database name
        - name: username
          description: Application username
        - name: password
          description: Application password

    - name: superuser-secret
      description: Superuser credentials
      type: secret
      keys:
        - name: username
          description: Superuser username
          default: "postgres"
        - name: password
          description: Superuser password

  # Best practices and recommendations
  recommendations:
    nonprod:
      - Use standard storage class for cost efficiency
      - Single instance is sufficient for development
      - Consider enabling monitoring for troubleshooting

    prod:
      - Always use HA cluster (3+ instances)
      - Enable automated backup with adequate retention
      - Use connection pooler for high-traffic applications
      - Configure pod anti-affinity for node failure resilience
      - Monitor replication lag and backup success
      - Use fast SSD storage for better performance
