apiVersion: v2
name: redis
description: Redis cache for microservices platform
type: application
version: 1.0.0
appVersion: "7.0"
keywords:
  - redis
  - cache
  - nosql
maintainers:
  - name: Platform Team
    email: platform@example.com
dependencies:
  - name: redis
    version: 17.3.14
    repository: https://charts.bitnami.com/bitnami