# App of Apps Pattern - Root Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/infraforge/gitops
    targetRevision: HEAD
    path: gitops/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
# Platform Project
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform components and infrastructure

  sourceRepos:
  - 'https://github.com/infraforge/*'
  - 'https://argoproj.github.io/argo-helm'
  - 'https://charts.bitnami.com/bitnami'
  - 'https://prometheus-community.github.io/helm-charts'
  - 'https://grafana.github.io/helm-charts'
  - 'https://kubernetes.github.io/ingress-nginx'
  - 'https://charts.konghq.com'

  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc

  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRole
  - group: 'rbac.authorization.k8s.io'
    kind: ClusterRoleBinding
  - group: 'apiextensions.k8s.io'
    kind: CustomResourceDefinition
  - group: 'admissionregistration.k8s.io'
    kind: ValidatingWebhookConfiguration
  - group: 'admissionregistration.k8s.io'
    kind: MutatingWebhookConfiguration
  - group: 'cert-manager.io'
    kind: ClusterIssuer
  - group: 'networking.k8s.io'
    kind: IngressClass

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

  roles:
  - name: platform-admin
    policies:
    - p, proj:platform:platform-admin, applications, *, platform/*, allow
    - p, proj:platform:platform-admin, repositories, *, *, allow
    groups:
    - platform-admins

  - name: platform-viewer
    policies:
    - p, proj:platform:platform-viewer, applications, get, platform/*, allow
    groups:
    - platform-viewers

---
# Tenant Projects ApplicationSet
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenant-projects
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/infraforge/gitops
      revision: HEAD
      directories:
      - path: gitops/tenants/*
  template:
    metadata:
      name: '{{path.basename}}-project'
    spec:
      project: platform
      source:
        repoURL: https://github.com/infraforge/gitops
        targetRevision: HEAD
        path: '{{path}}/project'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

---
# Platform Components ApplicationSet
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-components
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: observability
        namespace: monitoring
        path: gitops/platform/observability
      - name: security
        namespace: security
        path: gitops/platform/security
      - name: networking
        namespace: networking
        path: gitops/platform/networking
      - name: backstage
        namespace: backstage
        path: gitops/platform/backstage
      - name: kratix
        namespace: kratix-platform-system
        path: gitops/platform/kratix
      - name: cert-manager
        namespace: cert-manager
        path: gitops/platform/cert-manager
      - name: external-secrets
        namespace: external-secrets
        path: gitops/platform/external-secrets
      - name: velero
        namespace: velero
        path: gitops/platform/velero
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: platform
      source:
        repoURL: https://github.com/infraforge/gitops
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

---
# Environment-based ApplicationSet
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environment-apps
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/infraforge/gitops
          revision: HEAD
          directories:
          - path: gitops/environments/*
      - list:
          elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{path.basename}}-apps'
    spec:
      project: platform
      source:
        repoURL: https://github.com/infraforge/gitops
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: '{{url}}'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true