# ArgoCD Installation for Enterprise PaaS Platform
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    platform.infraforge.io/component: gitops
---
# Install ArgoCD using Helm
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.51.6
    chart: argo-cd
    helm:
      releaseName: argocd
      values: |
        global:
          domain: argocd.infraforge.io

        # Redis HA configuration
        redis-ha:
          enabled: true

        # Controller configuration
        controller:
          replicas: 1
          metrics:
            enabled: true
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi

        # Server configuration
        server:
          replicas: 2
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 5
          ingress:
            enabled: true
            ingressClassName: kong
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - argocd.infraforge.io
            tls:
              - secretName: argocd-server-tls
                hosts:
                  - argocd.infraforge.io
          metrics:
            enabled: true
          config:
            url: https://argocd.infraforge.io

            # OIDC configuration for SSO
            oidc.config: |
              name: Keycloak
              issuer: https://keycloak.infraforge.io/realms/platform
              clientId: argocd
              clientSecret: $oidc.keycloak.clientSecret
              requestedScopes: ["openid", "profile", "email", "groups"]
              requestedIDTokenClaims: {"groups": {"essential": true}}

            # RBAC configuration
            policy.csv: |
              p, role:platform-admin, *, *, */*, allow
              p, role:developer, applications, get, */*, allow
              p, role:developer, applications, sync, */*, allow
              p, role:developer, applications, action/*, */*, allow
              g, platform-admins, role:platform-admin
              g, developers, role:developer

            # Repository configuration
            repositories: |
              - type: git
                url: https://github.com/infraforge/gitops
              - type: helm
                url: https://charts.bitnami.com/bitnami
              - type: helm
                url: https://prometheus-community.github.io/helm-charts

        # Repo server configuration
        repoServer:
          replicas: 2
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 5
          metrics:
            enabled: true
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi

        # ApplicationSet controller
        applicationSet:
          enabled: true
          replicas: 2
          metrics:
            enabled: true

        # Notifications controller
        notifications:
          enabled: true
          argocdUrl: https://argocd.infraforge.io
          secret:
            create: true

          # Slack notifications
          notifiers:
            service.slack: |
              token: $slack-token

          subscriptions:
            - recipients:
              - slack:platform-alerts
              triggers:
              - on-sync-failed
              - on-health-degraded
              - on-deployed

          templates:
            template.app-deployed: |
              message: |
                Application {{.app.metadata.name}} is now running new version.
            template.app-health-degraded: |
              message: |
                Application {{.app.metadata.name}} has degraded health.
            template.app-sync-failed: |
              message: |
                Application {{.app.metadata.name}} sync failed.

        # Dex configuration (if not using external OIDC)
        dex:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m