apiVersion: v2
name: mongodb
description: MongoDB NoSQL database
type: application
version: 1.0.0
appVersion: "6.0"
keywords:
  - mongodb
  - nosql
  - database
maintainers:
  - name: Platform Team
    email: platform@example.com
dependencies:
  - name: mongodb
    version: 13.6.4
    repository: https://charts.bitnami.com/bitnami