apiVersion: v2
name: backend-service
description: Backend Service Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "v1.0.0"
keywords:
  - backend
  - api
maintainers:
  - name: Platform Team
    email: platform@example.com