apiVersion: platform.infraforge.io/v1
kind: ApplicationClaim
metadata:
  name: ecommerce-platform
  namespace: default
spec:
  namespace: dev
  environment: dev
  owner:
    team: Ecommerce Team
    email: ecommerce@infraforge.io

  applications:
    - name: product-service
      repository: https://github.com/infraforge/product-service
      version: v1.0.0
      image: 715841344657.dkr.ecr.eu-west-1.amazonaws.com/infraforge-dev/product-service:latest
      replicas: 2
      ports:
        - name: http
          port: 8080
      env:
        - name: DATABASE_URL
          value: postgresql://postgres@postgres:5432/products
        - name: REDIS_URL
          value: redis://redis:6379

    - name: user-service
      repository: https://github.com/infraforge/user-service
      version: v1.0.0
      image: 715841344657.dkr.ecr.eu-west-1.amazonaws.com/infraforge-dev/user-service:latest
      replicas: 2
      ports:
        - name: http
          port: 8081
      env:
        - name: DATABASE_URL
          value: postgresql://postgres@postgres:5432/users

    - name: order-service
      repository: https://github.com/infraforge/order-service
      version: v1.0.0
      image: 715841344657.dkr.ecr.eu-west-1.amazonaws.com/infraforge-dev/order-service:latest
      replicas: 3
      ports:
        - name: http
          port: 8082
      env:
        - name: DATABASE_URL
          value: postgresql://postgres@postgres:5432/orders
        - name: RABBITMQ_URL
          value: amqp://guest:guest@rabbitmq:5672

    - name: payment-service
      repository: https://github.com/infraforge/payment-service
      version: v1.0.0
      image: 715841344657.dkr.ecr.eu-west-1.amazonaws.com/infraforge-dev/payment-service:latest
      replicas: 2
      ports:
        - name: http
          port: 8083
      env:
        - name: DATABASE_URL
          value: postgresql://postgres@postgres:5432/payments

    - name: notification-service
      repository: https://github.com/infraforge/notification-service
      version: v1.0.0
      image: 715841344657.dkr.ecr.eu-west-1.amazonaws.com/infraforge-dev/notification-service:latest
      replicas: 2
      ports:
        - name: http
          port: 8084
      env:
        - name: RABBITMQ_URL
          value: amqp://guest:guest@rabbitmq:5672
        - name: SMTP_HOST
          value: smtp.gmail.com

  components:
    - type: postgresql
      name: postgres
      version: "14"
      config:
        size: "20Gi"
        replicas: "1"

    - type: redis
      name: redis
      version: "7.0"

    - type: rabbitmq
      name: rabbitmq
      version: "3.11"
