apiVersion: platform.infraforge.io/v1
kind: ApplicationClaim
metadata:
  name: test-app
spec:
  namespace: test
  environment: dev
  owner:
    team: platform-team
    email: platform@test.com
  applications:
    - name: nginx-app
      repository: nginx/nginx
      image: nginx
      version: latest
      replicas: 1
      ports:
        - name: http
          port: 80
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
